version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: cc_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cc_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cc_password}
      POSTGRES_DB: ${POSTGRES_DB:-cc_webapp_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-cc_user} -d ${POSTGRES_DB:-cc_webapp_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./cc-webapp/backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-cc_user}:${POSTGRES_PASSWORD:-cc_password}@db:5432/${POSTGRES_DB:-cc_webapp_db}"
      JWT_SECRET: ${JWT_SECRET:-dev_secret}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
