# 🔧 개발 환경용 Docker Compose Override
# docker-compose up 실행 시 자동으로 적용됨

version: '3.8'

services:
  # 백엔드 개발 설정
  backend:
    environment:
      DEBUG: true
      APP_ENV: development
      PYTHONUNBUFFERED: 1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app:cached  # 성능 향상을 위한 cached 옵션
      - backend_logs:/app/logs

  # 프론트엔드 개발 설정
  frontend:
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:${BACKEND_PORT:-8000}
      NEXT_PUBLIC_WS_URL: ws://localhost:${BACKEND_PORT:-8000}
    command: npm run dev
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
      - /app/.next

  # 개발용 Celery Worker
  celery-worker:
    environment:
      DEBUG: true
      APP_ENV: development
    command: celery -A app.core.celery_app worker --loglevel=debug --reload

  # 개발용 Celery Beat
  celery-beat:
    environment:
      DEBUG: true
      APP_ENV: development
    command: celery -A app.core.celery_app beat --loglevel=debug

volumes:
  backend_logs:
