"""add quiz tables

Revision ID: c298f11cabed
Revises: 4c54145429eb
Create Date: 2025-06-15 20:35:13.868400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c298f11cabed'
down_revision: Union[str, None] = '4c54145429eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('bet_amount', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('payout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('bet_amount', sa.Integer(), nullable=True),
    sa.Column('reward_amount', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_id'), 'quiz_sessions', ['id'], unique=False)
    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_options_id'), 'quiz_options', ['id'], unique=False)
    op.create_table('quiz_user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quiz_options.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_user_answers_id'), 'quiz_user_answers', ['id'], unique=False)
    op.alter_column('user_rewards', 'source_description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_user_rewards_awarded_at', table_name='user_rewards')
    op.drop_index('ix_user_rewards_reward_type', table_name='user_rewards')
    op.drop_index('ix_user_rewards_user_id', table_name='user_rewards')
    op.alter_column('user_segments', 'rfm_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_segments', 'risk_profile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_user_segments_rfm_group', table_name='user_segments')
    op.drop_index('ix_user_segments_risk_profile', table_name='user_segments')
    op.drop_index('ix_user_segments_user_id', table_name='user_segments')
    op.drop_column('user_segments', 'streak_count')
    op.drop_column('user_segments', 'last_updated')
    op.drop_column('user_segments', 'frequency_score')
    op.drop_column('user_segments', 'monetary_score')
    op.drop_column('user_segments', 'recency_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_segments', sa.Column('recency_score', sa.INTEGER(), nullable=True))
    op.add_column('user_segments', sa.Column('monetary_score', sa.INTEGER(), nullable=True))
    op.add_column('user_segments', sa.Column('frequency_score', sa.INTEGER(), nullable=True))
    op.add_column('user_segments', sa.Column('last_updated', sa.DATETIME(), nullable=True))
    op.add_column('user_segments', sa.Column('streak_count', sa.INTEGER(), nullable=True))
    op.create_index('ix_user_segments_user_id', 'user_segments', ['user_id'], unique=False)
    op.create_index('ix_user_segments_risk_profile', 'user_segments', ['risk_profile'], unique=False)
    op.create_index('ix_user_segments_rfm_group', 'user_segments', ['rfm_group'], unique=False)
    op.alter_column('user_segments', 'risk_profile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_segments', 'rfm_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_user_rewards_user_id', 'user_rewards', ['user_id'], unique=False)
    op.create_index('ix_user_rewards_reward_type', 'user_rewards', ['reward_type'], unique=False)
    op.create_index('ix_user_rewards_awarded_at', 'user_rewards', ['awarded_at'], unique=False)
    op.alter_column('user_rewards', 'source_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_quiz_user_answers_id'), table_name='quiz_user_answers')
    op.drop_table('quiz_user_answers')
    op.drop_index(op.f('ix_quiz_options_id'), table_name='quiz_options')
    op.drop_table('quiz_options')
    op.drop_index(op.f('ix_quiz_sessions_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
